#!/usr/local/bin/python3.11
# -*- coding: utf-8 -*-

# テスト実行するためのスクリプト

import re
import sys
from awslogs.bin import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
